In [11]:
import pandas as pd
import numpy as np
pd.__version__  
import fsspec
import sys
!{sys.executable} -m pip install -U fsspec huggingface_hub pandas

## Pour prendre le fichier entier

In [ ]:
import pandas as pd
import fsspec

files = fsspec.open_files(
    "hf://datasets/dmariaa70/METRAQ-Air-Quality/**/*.csv",
    expand=True
)

df = pd.concat(
    [pd.read_csv(f.open()) for f in files],
    ignore_index=True
)

df.head()

In [23]:
import pandas as pd

df = pd.read_csv("/Users/mmaggiora/Desktop/sample.csv", sep=";")

In [9]:
df.head()

,sensor_id,sensor_name,utm_x,utm_y,magnitude_id,magnitude_name,entry_date,value,is_interpolated
0,28079008,Escuelas Aguirre,442117.2366,4474770.696,12,NOX,2006-08-16 01:00:00,56.000000,False
1,28079039,Barrio del Pilar,439689.0496,4481081.619,88,RS,2024-03-21 05:00:00,1.045836,True
2,28079057,Sanchinarro,444026.8080,4482820.581,1023,OC_IDW,2020-03-13 00:00:00,0.000000,False
3,28079049,Parque del Retiro,442095.5200,4473981.740,89,PRECIPITACION,2021-01-30 04:00:00,0.000000,True
4,28079060,Tres Olivos,441556.7005,4483543.994,1023,OC_IDW,2023-12-19 09:00:00,15.933061,False

In [15]:
print(df.shape)

(100000, 9)

In [16]:
print(df.columns.tolist())

['sensor_id', 'sensor_name', 'utm_x', 'utm_y', 'magnitude_id', 'magnitude_name', 'entry_date', 'value', 'is_interpolated']

In [17]:
print(df.dtypes)

sensor_id            int64
sensor_name            str
utm_x              float64
utm_y              float64
magnitude_id         int64
magnitude_name         str
entry_date             str
value              float64
is_interpolated       bool
dtype: object

In [18]:
display(df.tail())

,sensor_id,sensor_name,utm_x,utm_y,magnitude_id,magnitude_name,entry_date,value,is_interpolated
99995,28079035,Plaza del Carmen,440346.3619,4474524.357,6,CO,2005-08-02 05:00:00,0.000000,False
99996,28079039,Barrio del Pilar,439689.0496,4481081.619,1002,TI_RBF_LINEAR,2019-10-06 10:00:00,247.788772,False
99997,28079040,Vallecas,444701.6871,4471043.010,1020,OC_RBF_MULTIQUADRIQ,2019-06-25 06:00:00,0.264563,False
99998,28079060,Tres Olivos,441556.7005,4483543.994,86,HR,2020-07-18 15:00:00,21.360293,True
99999,28079024,Casa de Campo,436598.5637,4474571.618,1024,OC_KRIGING,2016-04-01 05:00:00,2.723343,False

In [19]:
print(df.isna().sum())

sensor_id          0
sensor_name        0
utm_x              0
utm_y              0
magnitude_id       0
magnitude_name     0
entry_date         0
value              0
is_interpolated    0
dtype: int64

In [25]:
print("Rows:", len(df))
print("Sensors:", df["sensor_id"].nunique())
print("Sensor names:", df["sensor_name"].nunique())
print("Variables:", df["magnitude_name"].nunique())
print("Start date:", df["entry_date"].min())
print("End date:", df["entry_date"].max())

Rows: 100000
Sensors: 24
Sensor names: 24
Variables: 36
Start date: 2001-01-01 10:00:00
End date: 2024-12-31 20:00:00

In [26]:
coverage = df.groupby("magnitude_name")["entry_date"].agg(["min", "max", "count"])
display(coverage.sort_values("count", ascending=False))

                                         min                  max  count
magnitude_name
NOX                      2001-01-01 10:00:00  2024-12-30 03:00:00   6403
NO                       2001-01-01 14:00:00  2024-12-31 13:00:00   6397
NO2                      2001-01-01 22:00:00  2024-12-31 13:00:00   6268
O3                       2001-01-02 07:00:00  2024-12-30 11:00:00   3519
SP_RBF_LINEAR            2015-01-02 00:00:00  2024-12-30 17:00:00   3356
OC_IDW                   2015-01-03 06:00:00  2024-12-29 11:00:00   3310
SP_RBF_GAUSSIAN          2015-01-01 05:00:00  2024-12-31 15:00:00   3293
SP_IDW                   2015-01-01 14:00:00  2024-12-31 20:00:00   3284
OC_RBF_GAUSSIAN          2015-01-02 12:00:00  2024-12-31 20:00:00   3283
SP_RBF_MULTIQUADRIQ      2015-01-03 21:00:00  2024-12-31 09:00:00   3257
SP_KRIGING               2015-01-02 18:00:00  2024-12-31 10:00:00   3225
OC_RBF_LINEAR            2015-01-01 05:00:00  2024-12-31 01:00:00   3224
<PM10                    2001-01-05 16:00:00  2024-12-26 07:00:00   3221
OC_KRIGING               2015-01-05 01:00:00  2024-12-31 14:00:00   3192
OC_RBF_MULTIQUADRIQ      2015-01-03 02:00:00  2024-12-31 20:00:00   3137
TI_RBF_LINEAR            2015-01-02 08:00:00  2023-12-29 19:00:00   2975
TI_KRIGING               2015-01-01 11:00:00  2023-12-31 23:00:00   2941
TI_RBF_MULTICUADRIC      2015-01-01 19:00:00  2023-12-31 06:00:00   2907
TI_IDW                   2015-01-01 13:00:00  2023-12-30 06:00:00   2893
TI_RBF_GAUSSIAN          2015-01-01 00:00:00  2023-12-30 22:00:00   2887
SO2                      2001-01-02 14:00:00  2024-12-21 23:00:00   2789
CO                       2001-01-04 06:00:00  2024-12-26 12:00:00   2689
VV                       2019-01-02 08:00:00  2024-12-31 13:00:00   1981
PRE                      2019-01-01 13:00:00  2024-12-27 09:00:00   1965
RS                       2019-01-01 14:00:00  2024-12-30 03:00:00   1928
HR                       2019-01-02 04:00:00  2024-12-30 03:00:00   1913
DV                       2019-01-01 11:00:00  2024-12-27 08:00:00   1899
TEMP                     2019-01-02 22:00:00  2024-12-28 11:00:00   1896
PRECIPITACION            2019-01-01 05:00:00  2024-12-30 11:00:00   1885
<PM2.5                   2003-01-22 02:00:00  2024-12-31 08:00:00   1473
BENCENO                  2001-01-08 10:00:00  2024-12-26 10:00:00   1458
ETILBENCENO              2001-02-14 22:00:00  2024-12-24 06:00:00   1449
TOLUENO                  2001-01-26 12:00:00  2024-12-31 09:00:00   1395
HIDROCARBS_TOTALES       2001-01-14 13:00:00  2020-12-30 05:00:00    803
METANO                   2001-01-14 12:00:00  2020-12-29 12:00:00    783
HIDROCARBS_NO_METANICOS  2001-03-19 09:00:00  2020-12-27 08:00:00    722

In [27]:
sensor_coverage = df.groupby("sensor_name")["entry_date"].agg(["min", "max", "count"])
display(sensor_coverage.sort_values("count", ascending=False))

                                      min                  max  count
sensor_name
Casa de Campo         2001-01-01 22:00:00  2024-12-31 20:00:00   6720
Escuelas Aguirre      2001-01-04 02:00:00  2024-12-30 01:00:00   6441
Farolillo             2001-01-03 01:00:00  2024-12-30 03:00:00   5456
Cuatro Caminos        2001-01-10 12:00:00  2024-12-31 16:00:00   4983
Moratalaz             2001-01-08 15:00:00  2024-12-31 11:00:00   4526
Plaza del Carmen      2001-01-07 12:00:00  2024-12-31 15:00:00   4456
Urb. Embajada         2010-01-01 10:00:00  2024-12-31 09:00:00   4312
Vallecas              2001-01-07 15:00:00  2024-12-28 11:00:00   4206
Plaza de España       2001-01-04 02:00:00  2024-12-31 09:00:00   4181
Barajas Pueblo        2003-01-06 21:00:00  2024-12-31 11:00:00   4162
Arturo Soria          2001-01-01 14:00:00  2024-12-31 14:00:00   4159
Ramón y Cajal         2001-01-03 17:00:00  2024-12-31 20:00:00   4133
Barrio del Pilar      2001-01-01 10:00:00  2024-12-31 13:00:00   4043
Villaverde            2001-01-02 14:00:00  2024-12-31 17:00:00   3952
Sanchinarro           2010-01-02 08:00:00  2024-12-31 13:00:00   3712
Plaza Elíptica        2010-01-06 22:00:00  2024-12-31 20:00:00   3671
Castellana            2010-01-04 17:00:00  2024-12-27 18:00:00   3559
Plaza Castilla        2010-01-02 15:00:00  2024-12-30 13:00:00   3502
Méndez Álvaro         2010-01-04 14:00:00  2024-12-31 08:00:00   3441
El Pardo              2010-01-12 02:00:00  2024-12-29 12:00:00   3386
Parque del Retiro     2010-01-06 18:00:00  2024-12-28 22:00:00   3280
Juan Carlos I         2010-01-04 14:00:00  2024-08-24 07:00:00   3267
Ensanche de Vallecas  2010-01-02 05:00:00  2024-12-29 03:00:00   3258
Tres Olivos           2010-01-05 13:00:00  2023-12-31 22:00:00   3194